cache: bundler

env:
  global:
    - CC_TEST_REPORTER_ID=ff6f83857598f43ef357d0bd3828d8ffea9b29373dadf56da7b9be9e2a10ec62
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

language: ruby

rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.0
  - jruby-9.1.6.0
  - jruby-head
  - rbx-2
  - ruby-head

sudo: false

bundler_args: --without development --retry=3 --jobs=3

before_install:
  - gem update --system
  - gem update bundler
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rubocop
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  allow_failures:
    - rvm: jruby-9.1.6.0
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
